services:
  postgres:
    image: postgres:16
    container_name: singlevendor_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - singlevendor_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    mem_limit: 1024m
    cpus: "1.0"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: singlevendor_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - singlevendor_network
    networks:
      - singlevendor_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python3 -c ''import urllib.request; urllib.request.urlopen("http://localhost:80")''',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    mem_limit: 512m
    cpus: "0.5"

  redis:
    image: redis:7
    container_name: singlevendor_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    mem_limit: 512m
    cpus: "0.5"

  backend:
    image: carlostranquilinocr98/single-vendor-ecommerce-backend:latest 
    container_name: singlevendor_backend
    ports:
      - "8080:8080"
    networks:
      - singlevendor_network
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    mem_limit: 1024m
    cpus: "1"

  thumbnail-worker:
    image: carlostranquilinocr98/single-vendor-ecommerce-thumbnail-worker:latest
    container_name: singlevendor_thumbnail_worker
    env_file:
      - .env
    volumes:
      - ${FILE_DIRECTORY}:${FILE_DIRECTORY}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    mem_limit: 512m
    cpus: "0.5"

volumes:
  postgres_data:

networks:
  singlevendor_network:
    driver: bridge
